# Задание 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел
чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [8]:
a = np.arange(12, 24)

In [9]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

# Задание 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах
метода reshape число -1.

In [11]:
q = a.reshape(2,6)
w = a.reshape(3,4)
e = a.reshape(4,3)
r = a.reshape(6,2)
t = a.reshape(12,1)

In [12]:
q

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
w

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
e

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [15]:
r

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [16]:
t

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

# Задание 3 
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах
метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для
строк).

In [25]:
q = a.reshape(2,-1)
w = a.reshape(3,-1)
e = a.reshape(-1,3)
r = a.reshape(-1,2)
t = a.reshape(-1,1)

In [26]:
q

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [27]:
w

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
e

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [29]:
r

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [30]:
t

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

# Задание 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
Ответ: нет

# Задание 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой
из нормального распределения со средним, равным 0 и среднеквадратичным отклонением,
равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и
исходный массив.

In [31]:
a = np.random.randn(3, 4)

In [34]:
a

array([[ 1.33542173, -0.02869935, -1.64247152, -0.22570147],
       [-0.26982158, -1.33628978, -1.35515273, -0.63697809],
       [-1.68747763, -0.1901058 ,  1.08515148,  1.19343364]])

In [40]:
b = a.reshape(12)

In [41]:
b

array([ 1.33542173, -0.02869935, -1.64247152, -0.22570147, -0.26982158,
       -1.33628978, -1.35515273, -0.63697809, -1.68747763, -0.1901058 ,
        1.08515148,  1.19343364])

# Задание 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с
интервалом 2.

In [51]:
a = np.arange(19, 0, -2)

In [52]:
a

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

# Задание 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1
невключительно с интервалом 2. В чем разница между массивами a и b?

In [63]:
b = np.arange(19, 0, -2)
b = b.reshape(b.size, 1)

In [64]:
b

array([[19],
       [17],
       [15],
       [13],
       [11],
       [ 9],
       [ 7],
       [ 5],
       [ 3],
       [ 1]])

Разница между массивами а и б: массив а - одномерный, массив б - двумерный

# Задание 8 
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого
больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.

In [81]:
a = np.zeros((2, 2))

In [82]:
a

array([[0., 0.],
       [0., 0.]])

In [83]:
b = np.ones((3, 2))

In [84]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [85]:
v = np.concatenate((a, b), axis=0)

In [86]:
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [87]:
v.size

10

# Задание 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy),
состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и
почему?

In [27]:
a = np.arange(0, 12)

In [28]:
A = a.reshape(4, 3)

In [29]:
At = A.T

In [30]:
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [31]:
B = A.dot(At)

In [33]:
B.size

16

In [34]:
np.linalg.det(B)

0.0

для матрицы В не получиться вычислить обратную матрицу так как все значения в ней линейно зависимы и определитель = 0

# Задание 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [ ]:
np.random.seed(42)

# Задание 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных
равномерно распределенных целых чисел от 0 до 16 невключительно.

1 способ

In [69]:
c = np.random.randint(0, 16, size = 16, dtype = np.int16)

In [70]:
c

array([ 4, 10, 13,  0,  1, 11,  8,  4,  3,  0,  3,  7,  1,  7,  9, 10],
      dtype=int16)

2 способ

In [74]:
c = 16* np.random.sample((1, 16))

In [75]:
c = np.floor(c)

In [76]:
c

array([[14.,  3., 15.,  8.,  1., 10.,  3.,  5.,  8.,  4.,  8.,  4., 12.,
        12.,  3.,  5.]])

# Задание 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D,
поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [79]:
C = c.reshape(4, 4)

In [80]:
D = C + B

In [82]:
D = D.dot(10)

In [83]:
D

array([[ 190.,  170.,  380.,  400.],
       [ 150.,  600.,  890., 1270.],
       [ 310.,  900., 1570., 2160.],
       [ 440., 1340., 2150., 3070.]])

In [85]:
np.linalg.det(D)

1464350000.0000076

In [84]:
np.linalg.matrix_rank(D)

4

In [87]:
D_inv = np.linalg.inv(D)

In [88]:
D_inv

array([[ 0.00553829, -0.00840987, -0.00956738,  0.00948885],
       [ 0.00384676,  0.01584799, -0.00686721, -0.00222556],
       [ 0.00283266,  0.01190084,  0.01239389, -0.01401236],
       [-0.00445658, -0.01404651, -0.00431113,  0.0097504 ]])

# Задание 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции
numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве
источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых
соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему
элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы
D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [94]:
D_inv[D_inv < 0] = 0  

In [95]:
D_inv[D_inv > 0] = 1

In [96]:
D_inv

array([[1., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [98]:
C

array([[14.,  3., 15.,  8.],
       [ 1., 10.,  3.,  5.],
       [ 8.,  4.,  8.,  4.],
       [12., 12.,  3.,  5.]])

In [115]:
E = D_inv

In [118]:
E[E == 0] = C[np.where(E == 0)]

In [120]:
E[E == 1] = B[np.where(E == 1)]

In [121]:
E

array([[  5.,   3.,  15.,  32.],
       [ 14.,  50.,   3.,   5.],
       [ 23.,  86., 149.,   4.],
       [ 12.,  12.,   3., 302.]])